### ISSUE TITLE
Ghostmeme API Key for Atlanta

### ISSUE THREAD

**Issue by jamiekohns** [nhscc/problem-statements#2]
The Atlanta HSCC team requests an API key for the Ghostmeme problem.

**Comment by Xunnamius** [comment]
Hi! Have you been invited to the BDPA Slack? For security purposes, please DM me over Slack for a key.

**Comment by jamiekohns** [comment]
I have not been invited. I am the instructor/advisor to the Atlanta HSCC team

**Comment by Xunnamius** [comment]
Use this link to join: https://join.slack.com/t/bdpa-org/shared_invite/zt-spe49qyp-9QStkywfhMeJchQST4YqIA. You can invite others as well, though this link will expire in about 15 minutes.
